### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by guoxj** [robbdimitrov/RDVTabBarController#26]
when push a new viewcontroller,set the tabbar hide, then in the new viewcontroller, present a new viewcontroller, the tabbar got show. 
expected result: the tabbar still hide
Demo project can be download here: https://www.dropbox.com/s/yut6tc3awixsqig/RDVTabBarController-bug.zip

**Comment by code1303009** [comment]
when push a new viewcontroller,set the tabbar hide, then in the new viewcontroller, swipe to go back to first viewcontroller,offset of  the  contentview will be abnormal.
