### ISSUE TITLE
 UINavigationbar is under  status bar  

### ISSUE THREAD

**Issue by tentenlee100** [robbdimitrov/RDVTabBarController#49]
sometimes the UINavigationbar is under  status bar  like  the photo

![screen shot 2015-04-17 at 01 46 59](https://cloud.githubusercontent.com/assets/11982625/7187588/24084b00-e4a4-11e4-8580-558c2f842af4.png)

**Comment by yumincode** [comment]
Are you a developer from TaiWan?

**Comment by tentenlee100** [comment]
yes, from Taiwan.  This issue is other tool issue, please close it.

**Comment by cugbwxc** [comment]
【iOS9】我的应用也出现这个，页面起点在状态栏下隐藏。但是导航到下一个子页面，返回来，页面显示正常。请问有什么建议么？
