### ISSUE TITLE
push到一个页面隐藏tabbar,然后手势返回到一半的时候,tabbar直接显示出来,能直接点击tabbar

### ISSUE THREAD

**Issue by huahuazidingyi** [robbdimitrov/RDVTabBarController#73]
push到一个页面隐藏tabbar,然后手势返回到一半的时候,tabbar直接显示出来,能直接点击tabbar,就切换到其他页面了,返回到之前push 的那个页面,还是显示的是push进去的那个页面
![simulator screen shot 2016 11 22 11 48 15](https://cloud.githubusercontent.com/assets/13774717/20510205/d36dbb98-b0a9-11e6-9921-5f5795f07fae.png)

**Comment by Homosum** [comment]
我也是这个问题，so do I

**Comment by AlwaysYang** [comment]
在push 的页面 viewdidappear 里面，隐藏tabbar

**Comment by litianzhu818** [comment]
I think you had used the `RDVTabBarController` in the wrong way. you should use `RDVTabBarController` like this:
```objc
UIViewController *viewController1 = [UIViewController new];
UIViewController *viewController2 = [UIViewController new];
UIViewController *viewController3 = [UIViewController new];
UIViewController *viewController4 = [UIViewController new];

RDVTabBarViewController *tabBarViewController = [RDVTabBarViewController new];
[tabBarViewController setViewControllers:@[viewController1, viewController2, viewController3, viewController4]];
										 
UINavigationViewController *rootNavigationController = [[UINavigationViewController alloc] initWithRootViewController:tabBarViewController];									  

......

self.window.rootViewController = rootNavigationController;

``` 
not like this:

```objc
UIViewController *viewController1 = [UIViewController new];
UIViewController *viewController2 = [UIViewController new];
UIViewController *viewController3 = [UIViewController new];
UIViewController *viewController4 = [UIViewController new];

UINavigationViewController *navigationController1 = [[UINavigationViewController alloc] initWithRootViewController:viewController1];
UINavigationViewController *navigationController2 = [[UINavigationViewController alloc] initWithRootViewController:viewController2];
UINavigationViewController *navigationController3 = [[UINavigationViewController alloc] initWithRootViewController:viewController3];
UINavigationViewController *navigationController4 = [[UINavigationViewController alloc] initWithRootViewController:viewController4];

RDVTabBarViewController *tabBarViewController = [RDVTabBarViewController new];
[tabBarViewController setViewControllers:@[navigationController1, navigationController2, navigationController3, navigationController4]];
										  
......

self.window.rootViewController = tabBarViewController;

```

**Comment by macbookpro2100** [comment]
## 一，NavigationViewController滑动时屏蔽tabBar事件
当前viewWillDisappear 时 [self.rdv_tabBarController.tabBar setUserInteractionEnabled:NO];
里面层viewDidAppear时[self.rdv_tabBarController.tabBar setUserInteractionEnabled:YES];

add UIViewController+Swizzle.h
`#import <UIKit/UIKit.h>`
`@interface UIViewController (Swizzle)`
`@end`
`void swizzleAllViewController();`

add UIViewController+Swizzle.m
`#import "UIViewController+Swizzle.h"`
`#import <RDVTabBarController/RDVTabBarController.h>`

    @implementation UIViewController (Swizzle)
    - (void)customViewDidAppear:(BOOL)animated {
    
        [self.rdv_tabBarController.tabBar setUserInteractionEnabled:YES];
        [self customViewDidAppear:animated];
    }
    
    - (void)customViewWillDisappear:(BOOL)animated {
        [self.rdv_tabBarController.tabBar setUserInteractionEnabled:NO];
    
        [self customViewWillDisappear:animated];
    }
    
    - (void)customviewWillAppear:(BOOL)animated {
        [self customviewWillAppear:animated];
    }
    
    
    + (void)load {
        swizzleAllViewController();
    }
    @end
    
    void swizzleAllViewController() {
        Swizzle([UIViewController class], @selector(viewDidAppear:), @selector(        customViewDidAppear:));
        Swizzle([UIViewController class], @selector(viewWillDisappear:), @selector(        customViewWillDisappear:));
        Swizzle([UIViewController class], @selector(viewWillAppear:), @selector(        customviewWillAppear:));
    }
 



// 方法交换 
void Swizzle(Class claz, SEL originalSelector, SEL swizzledSelector)
{
    
    Method originalMethod = class_getInstanceMethod(claz, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(claz, swizzledSelector);
    
    
    BOOL didAddMethod =
    class_addMethod(claz,
                    originalSelector,
                    method_getImplementation(swizzledMethod),
                    method_getTypeEncoding(swizzledMethod));
    
    if (didAddMethod){
        class_replaceMethod(claz,
                            swizzledSelector,
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }
    
}


## 二 ，push hiden tabbar 参照[Coding方案](https://github.com/Coding/Coding-iOS/blob/master/Coding_iOS/Util/OC_Category/UIViewController%2BSwizzle.m)

**Comment by macbookpro2100** [comment]
## 一，NavigationViewController滑动时屏蔽tabBar响应
里面层customviewWillAppear时 [self.rdv_tabBarController.tabBar setUserInteractionEnabled:NO];
里面层viewDidAppear时[self.rdv_tabBarController.tabBar setUserInteractionEnabled:YES];

add UIViewController+Swizzle.h
`#import <UIKit/UIKit.h>`
`@interface UIViewController (Swizzle)`
`@end`
`void swizzleAllViewController();`

add UIViewController+Swizzle.m
`#import "UIViewController+Swizzle.h"`
`#import <RDVTabBarController/RDVTabBarController.h>`

    @implementation UIViewController (Swizzle)
    - (void)customViewDidAppear:(BOOL)animated {
    
        [self.rdv_tabBarController.tabBar setUserInteractionEnabled:YES];
        [self customViewDidAppear:animated];
    }
    
    - (void)customViewWillDisappear:(BOOL)animated {
        [self customViewWillDisappear:animated];
    }
    
    - (void)customviewWillAppear:(BOOL)animated {
        [self.rdv_tabBarController.tabBar setUserInteractionEnabled:NO];
        [self customviewWillAppear:animated];
    }
    
    
    + (void)load {
        swizzleAllViewController();
    }
    @end
    
    void swizzleAllViewController() {
        Swizzle([UIViewController class], @selector(viewDidAppear:), @selector(        customViewDidAppear:));
        Swizzle([UIViewController class], @selector(viewWillDisappear:), @selector(        customViewWillDisappear:));
        Swizzle([UIViewController class], @selector(viewWillAppear:), @selector(        customviewWillAppear:));
    }
 



// 方法交换 
void Swizzle(Class claz, SEL originalSelector, SEL swizzledSelector)
{
    
    Method originalMethod = class_getInstanceMethod(claz, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(claz, swizzledSelector);
    
    
    BOOL didAddMethod =
    class_addMethod(claz,
                    originalSelector,
                    method_getImplementation(swizzledMethod),
                    method_getTypeEncoding(swizzledMethod));
    
    if (didAddMethod){
        class_replaceMethod(claz,
                            swizzledSelector,
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }
    
}


## 二 ，push hiden tabbar 参照[Coding方案](https://github.com/Coding/Coding-iOS/blob/master/Coding_iOS/Util/OC_Category/UIViewController%2BSwizzle.m)
