### ISSUE TITLE
如何让RDVTabBarItem的image做动画?

### ISSUE THREAD

**Issue by fuchenxi** [robbdimitrov/RDVTabBarController#76]
点击RDVTabBarItem如何让image做一个放大缩小的动画, 和一个下沉位移的动画?请教一下实现思路

**Comment by eggswift** [comment]
@fuchenxi 我开源了一个支持动画的自定义tabbar组件，你可以用这个做自定义的动画~
https://github.com/eggswift/ESTabBarController
