### ISSUE TITLE
iphoneX的tabbar高度不一样了   求解决

### ISSUE THREAD

**Issue by yushan023** [robbdimitrov/RDVTabBarController#82]

**Comment by sunzhongliangde** [comment]
什么意思，这个是自定义的tabbar，提供有方法设置tabbar高度的。
/**
 * Sets the height of tab bar.
 */
- (void)setHeight:(CGFloat)height;

**Comment by yushan023** [comment]
不是   这个属性没用额   我要设配iphoneX

**Comment by faimin** [comment]
为什么不用英文提问？你认为作者看得懂中文？

**Comment by MrDangerous** [comment]
RDVTabBarController *tabBarController = 
    
[tabBarController.tabBar setHeight:@"49 或者83的动态宏定义"];

试试

**Comment by yushan023** [comment]
说了setHeight没用了

**Comment by sd1435728** [comment]
我测试使用setHeight 是有效的

**Comment by MrDangerous** [comment]
我也使用的RDVTabBarController,已经适配好了

**Comment by chenxinjie1129** [comment]
设置height，设置ContentEdgeInsets，就OK拉

**Comment by teemo2015** [comment]
设置height，设置ContentEdgeInsets，中的ContentEdgeInsets这个怎么设置的

**Comment by teemo2015** [comment]
@yushan023 适配解决了没

**Comment by HuangWei201703** [comment]
`
[self.tabbarVC.tabBar setHeight:83];
[self.tabbarVC.tabBar setContentEdgeInsets:UIEdgeInsetsMake(18, 0, 0, 0)];
`

**Comment by sunzhongliangde** [comment]
@HuangWei201703  这样解决的话，badgevalue坐标不对了

**Comment by sunzhongliangde** [comment]
@HuangWei201703  已解决好，还需要重设一下RDVTabBarItem的badgePositionAdjustment
`if(iPhoneX) {
            item.badgePositionAdjustment = UIOffsetMake(0, 18);
        }`

**Comment by xxuueeyyaann** [comment]
@sunzhongliangde 请问一下具体在哪设置啊

**Comment by ax654123123** [comment]
- (void)setupViewControllers {
    XSHomeViewController *firstViewController = [[XSHomeViewController alloc] init];
    UINavigationController *firstNavigationController = [[UINavigationController alloc]
                                                   initWithRootViewController:firstViewController];

    XSPublicationViewController *secondViewController = [[XSPublicationViewController alloc] init];
    UINavigationController *secondNavigationController = [[UINavigationController alloc]
                                                    initWithRootViewController:secondViewController];

    XSMineViewController *thirdViewController = [[XSMineViewController alloc] init];
    UINavigationController *thirdNavigationController = [[UINavigationController alloc]
                                                   initWithRootViewController:thirdViewController];

    RDVTabBarController *tabBarController = [[RDVTabBarController alloc] init];
    [tabBarController setViewControllers:@[firstNavigationController,
                                           secondNavigationController,
                                           thirdNavigationController]];
    self.tabBarController = tabBarController;
    if (KIsiPhoneX) {
        [self.tabBarController.tabBar setHeight:83];
        [self.tabBarController.tabBar setContentEdgeInsets:UIEdgeInsetsMake(18, 0, 0, 0)];
    }
    [self customizeTabBarForController:tabBarController];
}

- (void)customizeTabBarForController:(RDVTabBarController *)tabBarController {

    NSArray *tabBarItemImages = @[@"tab-home", @"tab-fabu", @"tab-my"];
    NSArray *tabBarItemTitles = @[@"首页", @"发布", @"我的"];

    NSInteger index = 0;
    for (RDVTabBarItem *item in [[tabBarController tabBar] items]) {

        if(KIsiPhoneX) {
            item.badgePositionAdjustment = UIOffsetMake(0, 18);
        }
        
        UIImage *selectedimage = [UIImage imageNamed:[NSString stringWithFormat:@"%@-Select",
                                                      [tabBarItemImages objectAtIndex:index]]];
        UIImage *unselectedimage = [UIImage imageNamed:[NSString stringWithFormat:@"%@-default",
                                                        [tabBarItemImages objectAtIndex:index]]];
        [item setFinishedSelectedImage:selectedimage withFinishedUnselectedImage:unselectedimage];

        item.title = [NSString stringWithFormat:@"%@",[tabBarItemTitles objectAtIndex:index]];
        item.unselectedTitleAttributes = @{
                                           NSFontAttributeName: [UIFont systemFontOfSize:10],
                                           NSForegroundColorAttributeName: UIColorFromRGB(0X8A8A8A)
                                           };
        item.selectedTitleAttributes = @{
                                           NSFontAttributeName: [UIFont systemFontOfSize:10],
                                           NSForegroundColorAttributeName: UIColorFromRGB(0XFF6E00)
                                           };
        index++;
    }
}

**Comment by Charlschun** [comment]
上面的伸手党也好意思说作者不回答，作者直接替你写代码算了，遇到问题自己多尝试，解决问题的能力都没有

**Comment by TonyTong1993** [comment]
viewDidLayoutSubviews 
if (!tabBarHeight) {
        if (@available(iOS 11.0, *)) {
            CGFloat safeAreaBottom = UIApplication.sharedApplication.keyWindow.safeAreaInsets.bottom;
            tabBarHeight = 58.f + safeAreaBottom / 1.5f;
        } else {
            tabBarHeight = 58.f;
        }
    } else if (@available(iOS 11.0, *)) {
        CGFloat safeAreaBottom = UIApplication.sharedApplication.keyWindow.safeAreaInsets.bottom;
        tabBarHeight = 58.f + safeAreaBottom / 1.5f;
    }
这里会重新设置tab的高度，所以tabBar setHeight:没啥用，继承tabController重写viewDidLayoutSubviews
