### ISSUE TITLE
Changes for iPhoneX

### ISSUE THREAD

**Issue by prgorasiya** [robbdimitrov/RDVTabBarController#84]
I am using this tab bar for my app and I am working on fixing the position issue for iPhoneX because of course current code doesn't support safe area layout guides.

So how can I get rid of this issue?

My tabbar looks like this.

![simulator screen shot - iphone x - 2017-11-13 at 12 05 46](https://user-images.githubusercontent.com/11789986/32709423-45bf2568-c86b-11e7-9e1d-2d40ccb35a69.png)

Please help.
Thanks

**Comment by AcidicSkittles** [comment]
I just did a temporary hack. This isn't a viable solution. But if you're lazy and want a dirty solution, might be worth a try.

```Objective-C
CGFloat bottomPadding = 0;
CGFloat desiredTabbarHeight = 49.0
if (@available(iOS 11.0, *)) {
    //get the height of the "unsafe" area and align our tabbar above it
    UIWindow *window = UIApplication.sharedApplication.keyWindow;
    bottomPadding = window.safeAreaInsets.bottom;
    
    //I added a view to prevent the "unsafe" part of the tabbar from being touchable.
    if(bottomPadding > 0)
    {
    	UIView *blocker = [[UIView alloc] initWithFrame:CGRectMake(0, desiredTabbarHeight, self.tabBar.bounds.size.width, bottomPadding)];
    	blocker.autoresizingMask = UIViewAutoresizingFlexibleWidth;
    	[self.tabBar addSubview:blocker];
    }
}

[self.tabBar setHeight:desiredTabbarHeight + bottomPadding];

//..your code to add the tab items and controllers

for(RDVTabBarItem *item in self.tabBar.items) {
    //offset the tabbar icons to be above the safe area
    if(bottomPadding > 0)
        item.imagePositionAdjustment = UIOffsetMake(0, -(bottomPadding/2));
}
```

**Comment by HuangWei201703** [comment]
`[self.tabbarVC.tabBar setHeight:83];`

`[self.tabbarVC.tabBar setContentEdgeInsets:UIEdgeInsetsMake(18, 0, 0, 0)];`

**Comment by lvpeng0412** [comment]
setHeight无效，
setContentEdgeInsets:没有这个方法啊
@HuangWei201703

**Comment by prgorasiya** [comment]
@AcidicSkittles @HuangWei201703 
I ended up doing pretty much the same thing.
I added a check for identifying iPhone X and increased the height of tabBar view and also used setContentEdgeInsets to reposition all those tabBar items just for iPhone X.
Thats working pretty fine throughout the app but I believe in future something will change and this would break.

**Comment by apwelsh** [comment]
Any update on an official solution for iPhone X support?  Is it now preferable to just use the UITabBarController instead?

**Comment by apwelsh** [comment]
After several attempts to find a good solution w/o having to change the source of this project (as the last PR was so long ago) I removed this control, and wen to the standard UITabBarController.
